name: Passing Values to Next Jobs

on: workflow_dispatch

jobs:

    job1:
        runs-on: ubuntu-latest

        # Map a step outout to a job output
        outputs:
            outputs1: ${{ steps.step1.outputs.test }}
            outputs2: ${{ steps.step1.outputs.test }}

        steps:
            - id: step1
              run: echo "test=ImportantValue1" >> $GITHUB_OUTPUT
            - id: step2
              run: echo "test=ImportantValue2" >> $GITHUB_OUTPUT

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - run: |
                echo "Printing the values"
                echo output1: ${{ needs.job1.outputs.outputs1}}
                echo output2: ${{ needs.job1.outputs.outputs2}}